export default {
    titleNav:'Whale tracking',
    des:'Supports {chain} public chains, {href} popular protocols, and contains {addressNum}+ addresses with assets over 10 million',
    follow:'Track',
    followNo:'Cancel traking',
    order:'Sort by',
    notic:'Reminder of address change',
    lookMore:'View more',
    account:'Account balance',
    myName:'Modify Remarks',
    share:'Recommend to friends',
    updateTip:'Data updated 20 minutes ago',
    history:'Transaction history',
    allChain:'All chains',
    all:'All',
    findSearchTip:'Enter the address to search',
    searchTip:'Enter token to filter',
    searchGlobal:'Search address',
    lastPay:'Recent transaction',
    back:'Back',
    noFollow:{
        title:`You are not following the address`,
        go:'Go to',
        tag:'Popular Address',
        des:'and add the address of a big account you follow'
    },
    followDialog:{
        title:`Add/Edit notes to this address`,
        tip:'Please enter address remarks',
        tiao:'Skip',
        ok:'Confirm',
        no:'Cancel'
    },
    success:'success',
    fillter:{
        fund:'Asset',
        rate:'Rate of return',
        time:'Recently active time',
    },
    find: {
        fund:'Account balance',
        rate:'Rate of return',
        change:'Balance Change',
        nav:'Whale addresses',
        my:'Followed',
        list:'Hot',
        info:'The (RoR) rate of return is the statistical value since the address was included, and the included time is {time} (UTC-8)'
    },
    change: {
        nav:'Address alerts',
        my:'Followed',
        list:'Hot',
    },
    seo:{
        title:`Whale Address Tracking`,
        key:`whales, whale address, documentary, SBF, Justin Sun, Three Arrows Capital, VGod, chain tracking, address tracking, asset tracking, whale token address, whale wallet address, bitcoin whale wallet address, ETH whale wallet address`,
        des:`KingData whales alert allows to live track large whale wallet addresses and big financial movements on the blockchains`,
    },
    money:{
        deposit:'Deposit',
        liabilities:'Liabilities',
        earnings:'Earnings',
        charge:'Accumulated consumption service charge',
        moreLook:'To learn more expand the box',
        close:'Put away',
        moneyDis:'Asset Distribution',
        payHistory:'Transaction History',
        wallet:'Wallet',
        agreement:'Agreement',
        more:'Load More',
        roundTitle:'Chain Asset Distribution',
        barTitle:'Protocol Distribution',
        look:'Asset Overview',
        sum:'Total Assets',
        account:'Account Assets',
        walter:'Wallet Assets',
        zichan:'Assets',
        number:'Amount',
        zhanbi:'Proportion',
        jiage:'Price',
        jiazhi:'Value',
        reward:'Yield/Reward',
        kingInfo:'Recommend Tokens & Protocols to us',
        valueTip:'Apy is estimated based on the rate of return in the current statistical time'
    },
    awaitData:`Data loading, it will take 30s ~ 2m for the first loading, please wait a moment`,
    noData:'No Data',
    payPrice:'Trading value',
    payType:'Trading types',
    filterTag:'Tags',
    historyHeader:{
        typeTime:'Type/Time',
        send:'Send',
        received:'received',
        payPrice:'Trading value',
        payObject:'Trading Objects',
    }
}