export default {
  disclaimers: "Disclaimers",
  title: "Early Find and Invest High APY Pools",
  apply: "Apply",
  projectType: {
    all: "All",
    mining: "Mining",
    lending: "Lending",
  },
  miningTitle: "Early Find and Invest High APY Pools",
  loanTitle: "Find the Lowest APR Path to Borrow",
  platDes: "{chain} chains, {project} projects, {pool} pools, support for cross-chain comparison, historical trends, APP reminder",
  allChain: "All Chain",
  chain: "Chain",
  loanListChain: "Chain",
  searchTxt: "Search",
  searchProject: "Search",
  search: "Search",
  notice: "Announcement",
  tutorial: "Tutorial",
  selectPlat: "Select Platform",
  selectCoin: "Select Token",
  playType: {
    plat: {
      title: "Have Selected Project",
      des1: "Find the",
      high: "Highest",
      des2: "APY token",
    },
    coin: {
      title: "Have Token",
      des1: "Find the",
      high: "Highest",
      des2: "APY project",
    },
    loan: {
      title: "Want To Borrow",
      des1: "Find the",
      high: "Lowest",
      des2: "APR project",
    },
  },
  my: "Favorite",
  total: "Compound APY",
  single: "Token APR",
  more: "Load more",
  miningChartTitle: "Token Farm APY",
  loanChartTitle: "Token Borrow APY",
  chainType: "Chain",
  poolType: "Type",
  poolTag: "Tag",
  apyGroup: "APY Info",
  singleInterest: "Single", // 'Token APR',
  compoundInterest: "Compound", // 'Compound APY',
  remainRatio: "Remaining",
  hasMoney: "Remaining",
  remainHasMoney: "Remaining",
  miningFarm: "Deposit",
  lendFarm: "Borrow",
  viewChart: "Chart",
  viewToken: "View Token",
  searchAll: "Search Token/Project",
  project: "Project",
  projectTutorial: "Tutorial",
  comLink: "Link",
  pools: "Pools",
  tokens: "Token",
  highApy: "Highest APY",
  ok: "OK",
  moreToken: "More Tokens",
  selectCoins: "More",
  farmApyList: "Farm APY List",
  loanList: "Borrow APY List",
  realCalculator: "Real Borrow APR calculator",
  calculator: "Calculator",
  lever: "Margin",
  projects: "Projects",
  all: "All",
  singleCoin: "Token",
  operate: "Operate",
  loanCoin: "Borrow",
  borrowMoney: "Liquidity",
  borrowAmount: "Liquidity",
  interestGroup: "APY Info",
  loanListDes: "The Best Way To Borrow",
  plat: "Project",
  mortgage: "Supply APY",
  borrowApy: "Borrow APR",
  borrowNumber: "Borrow Remaining",
  cost: "True Cost",
  projectTvl: "TVL(Multi-chain)",
  userMoney: "User Revenue(Multi-chain)",
  supprotChain: "Supproted Chain",
  poolNumber: "Pools",
  projectView: "Project Overview",
  addPool: "Add Pools",
  unaudited: "Unaudited",
  dayUser: "Daily Active Users",
  projectRevenue: "Project Revenue",
  platCoinPrice: "Platform Token Price",
  sameProjectData: "Relative Projects Data",
  loanRouter: "The Best Way To Borrow {value}",
  lowestLtv: "Lowest LTV",
  clearRatio: "Liquidation Ratio",
  mortgageInterest: "Supply APY",
  rankCompare: "Ranking comparison",
  trend: "Trending",
  trendCompare: "Trending comparison",
  poolCompare: "Pools comparison",
  relatedLoanTrend: "Related Loan Indicator Trending",
  loanTopBest: "{value}  Borrowing TOP 5 Borrow APR comparison",
  unitTiao: "",
  projectDes: "Introduction",
  timeFormat: "YYYY-M-DD",
  miningPool: "Farm Pools",
  loanPool: "Borrow Pools",
  projectData: "Project Data",
  selectedPool: "Selected Pools",
  allMiningPool: "All Farm Pools",
  allLoanPool: "All Borrow Pools",
  addLoanPool: "Add Borrow Pools",
  projectLook: {
    userMoney: "Revenue",
    borrowMoney: "Borrows",
    intoMoney: "Deposits",
    poolNumber: "Pools",
    singlePoolNumber: "Token Pools",
    lpPoolNumber: "LP Pools",
    unit: "",
  },
  addProject: "Add Project",
  selectedProject: "Selected Project",
  loanMoneyCoin: "Token",
  loanApr: "Borrow APR",
  miningApy: "Mining APY",
  noData: "Oops! No data found",
  loanPlat: "Project",
  pleaseSelect: "Select",
  diyaCoin: "Supply Token",
  diyaRato: "LTV",
  jiechuCoin: "Borrow Token",
  jiekuanMoney: "Cost",
  nowRato: "Current LTV",
  noLow: "No less than",
  realRato: "Borrow APR",
  clearData: "Reset",
  loanAllRouter: "All Best Ways To Borrow {token}",
  warning: "Waring",
  description: "Risk warning: the data of this station comes from the public data of various platforms.",
  warningDes: "The data of this station comes from the public data of various platforms. The safety audit of the included contents is not conducted in this station, and the contents do not constitute investment suggestions. Please pay attention to the risks.",
  tokenMining: "All Farm APY",
  tokenLending: "All Borrow APR",
  tokenMiningTitle: "{token} APY TOP 5 Pools",
  tokenLendingTitle: "{token} Borrow APR Top 5 Pools",
  tokenMiningListTitle: "{token} ALL POOLS APY",

  topTitleMining: "{token} Top 5",
  topTitleLending: "{token} Top 5",
  projectTitleMining: "Current APY Top 5 Pools",
  projectTitleLending: "Current APR Top 5 Pools",
  tokenTitleMining: "Current {token} Farm APY TOP 5",
  tokenTitleLeding: "Current {token} Borrow APR TOP 5",
  goMining: "Deposit",
  goLending: "Borrow",

  pageMining: {
    title: "Be the first to invest in most profitable liquidity pools",
    content: "Include 5 public chains, 25 projects, 1422 pools",
  },
  pageLoan: {
    title: "Find the Lowest APR Path to Borrow",
    content: " Include 5 public chains, 25 projects, 1422 pools",
  },
  pageProject: {
    title: "{project} Project data analysis",
    content: "Include 5 public chains, 25 projects, 1422 pools",
    h3: {
      mining: "{project} Farm APY Top 5 {pool}",
      loan: "{project} Borrow APR Top 5 {pool}",
      data: "{project} {value}",
    },
  },
  pageToken: {
    title: "{symbol} APY Comparison",
    content: "Include 5 public chains, 25 projects, 1422 pools",
  },
  pageHeco: {
    title: "The First HECO Node Election Data",
    content: "Comparison of HECO node election data trending",
  },
};
