export default {
  test: "Evaluation",
  testDes: "You can be a reviewer by posting awesome reviews and join in our discussion group to exchange views with big shots in this industry.",
  testing: "Write",
  inputTip: "Talk about your views on the project ~",
  become: "Become an author",
  min: "minute ago",
  hour: "hour ago",
  day: "day ago",
  month: "month ago",
  year: "year ago",
  push: "Post",
  reply: "Reply",
  top: "Top",
  more: "More",
  close: "Close",
  moreTest: "More...",
  delete: "Delete",
  success: "Success",
  warning: {
    min: "Less than {count} words",
    max: "More than {count} words",
  },
  write: "Write reviews",
};
