export default {
  login: "Log In",
  register: "Sign Up",
  apply: "Apply",
  more: "More",
  idea: "Idea",
  resetPassword: "Reset Password",
  switchLogin: "Log In",
  switchRegister: "Create Account",
  switchRorget: "Forgot Password",
  phone: "Phone",
  email: "Email",
  phoneCreate: "Phone",
  emailCreate: "Email",
  phoneForget: "Phone",
  emailForget: "Email",
  emailUpdate: "Email",
  noData: "No Data",
  lang: "CN",
  loginOut: "Log Out",
  reviews: "kingData operate reviews",
  copyOk: "Copy success",
  account: {
    email: {
      tips: "Please connect your email",
      bind: "Go",
      bind2: "Connect Email",
    },
  },
  nav: {
    apply: "Project Application",
    about: { name: "About", href: "https://kingdata.medium.com/about-kingdata-growthpad-36907c18440c" },
    download: "Download KingData APP",
    download2: "Download APP",
  },
  time: {
    date: "Date",
    dd: "Days",
    hh: "Hours",
    mm: "Minutes",
    ss: "Seconds",
    value: {
      week: "no week | 1 week ago | {count} weeks ago", // 几周前
      day: "no day | 1 day ago | {count} days ago", // 几天前
      hour: "no hour | 1 hour ago | {count} hours ago", // 几小时前
      minute: "no minute | 1 minute ago | {count} minutes ago", // 几分钟前
    },
    ago: "{date} ago",
    // 星期几
    week: "Monday | Tuesday | Wednesday | Thursday | Friday | Saturday | Sunday",
    month: "Jan | Feb | Mar | APR | May | Jun | Jul | Aug | Sep | Oct | Nov | Dec",
    startTime: "Start Time",
    endedTime: "Remaining time",
    countDown: {
      // 未开始
      started: {
        day: "start in {count} days",
        hour: "start in {count} hours",
        minute: "start in {count} minutes",
      },
      // 未结束
      ended: {
        day: "ends in {count} days",
        hour: "ends in {count} hours",
        minute: "ends in {count} minutes",
      },
    },
  },
  title: {
    share: "Share",
  },
  button: {
    copy: "Copy",
    submit: "Submit",
    confirm: "Confirm",
    close: "Close",
    review: "In Review",
    success: "Completed",
    danger: "Not approved",
    selected: "Selected",
    more: "Load More",
    share: "Share",
    all: "All",
    viewAll: "View All",
    goto: "Go to",
    prev: "Prev",
    next: "Next",
    shut: "Close",
    expandMore: "More | More ({size})",
  },
  message: {
    verification: "Send",
    verificationError: "Please enter the 6-digit verification code",
    passwordError: "Please enter the 6-24 digit of password!",
    new_password: "The password must be consistent",
    telError: "Please enter valid phone number",
    checked: "Please read and agree before registering",
    mailError: "Email format is incorrect",
    copyAlert: "Copy successfully",
    testing: "Verifying. About 15 minutes.", // 验证中，审核结束后自动更新结果
    checking24h: "Verifying. About 24 hours",
    get: "Get",
    copy: "The link has copied",
    fail: "Validation failed",
    checkValue: "Please slide to verify",
    codeDialog: "Slide to get the verification code",
    loginError: "Incorrect account or password input!",
  },
  placeholder: {
    login: "Automatic log-in",
    tel: "Please enter your phone number",
    email: "Please enter your email",
    verification: "Please enter verification code",
    password: "Please enter the password",
    new_password: "Please enter your password again",
    search: "Search",
    sort: "Sort order",
  },
  and: "And",
  join: "Join",
  follow: "Follow",
  repost: "Retweet",
  andRepost: "And Retweet",
  activity: "Activity",
  user: {
    invite: "Please enter the invitation code (optional)",
    read: "I have read and agree to the ",
    agreement: "《Service agreement》",
    terms: "《Terms of service》",
    use: "《Instructions of use》",
    push: "I areee to receive promotional and marketing material",
  },
  chat: {
    telegram: "Telegram",
    join: "Join",
    telegramGroup: "Telegram Group",
    joinTelegram: "Join Telegram",
    twitter: "Twitter",
    sina: "Weibo",
  },
  symbol: {
    plus: "+",
    divide: "Divide ",
    colon: ": ",
  },
  api: {
    wrong: "System exception",
  },
  fixTip: {
    content1: "Learn, communicate",
    content2: "And",
    content3: "Feedback questions",
    comfirm: "Join Telegram",
  },
  risk: {
    high: "High Risk",
    medium: "Medium Risk",
    low: "Low Risk",
    unknown: "Unknown Risk",
  },
  site: {
    web: "Website",
    name: "Website",
  },
  dialogData: {
    tip: "Tip",
    deleteDes: "The content cannot be restored after deletion. Are you sure you want to delete this review/response?",
    close: "Close",
    ok: "Ok",
  },
  lock: {
    text1: "Enjoy the great airdrop and share them with your friends",
    text2: "Valid ways to share",
    gain: "Get",
    again: "Keep Sharing",
    unlock: "more friends <i>to click on this link</i> to help you unlock the full content",
    shared: "View Progress",
    success: "Unlock Full Content",
    progress: "Unlock progress",
  },
  share: {
    telegram: "Share On Telegram",
    twitter: "Share On Twitter",
    link: "Copy links to share with groups or friends",
  },
  validate: {
    title: "Dear User:",
    desc: "This website does not support users from mainland China.Please confrm that you are not from the above countries or regions before visiting.",
  },
};
