import { oss } from "src/config/";
export default {
  title: "Early to invest high ROI DeFi project",
  apply: "Apply",
  group: {
    all: "All",
    viewOnline: "Live projects",
    search: "Search",
  },
  header: {
    info: "Project information",
    mediaData: "Media data",
    type: "Type",
    time: "Online time (UTC)",
    operate: "Operate",
    projectYield: "Project benefits",
  },
  website: "Go",
  timeEnd: "Time left",
  sort: {
    timeDesc: "Descending by online time",
    timeAsc: "Ascending by online time",
    priceDesc: "Descending by price",
    priceAsc: "Ascending by price",
    clout: "Sort by popularity",
    create_time: "Sort by latest time",
    rec: "REC",
    history: "Ended",
    online: "Upcoming",
  },
  status: {
    success: `${oss}/image/dapp/ongoing_en.png`,
    wait: "/assets/dapp/wait_en.png",
  },
  page: {
    title: "KingData New DApp Ranking",
    content: "Discover the latest DApps, DeFi, NFT, Games, websites that everyone's talking about.",
  },
  meta: {
    description: "KingData New DApp Ranking Discover the latest DApps, DeFi, NFT, Games, websites that everyone's talking about.",
  },
  rank: {
    title: "Early Find High-quality DApps",
    chartTitle: "Total TVL of all chains",
    comparison: "Comparison",
    searchProject: "Search",
    page: {
      title: "KingData DApp Ranking",
      content: "Quickly discover popular DApps, DeFi, NFTs, games and websites",
      meta: "KingData DApp Ranking is a curation of the best new dapp products, every day. Discover the latest DApps, websites, Games, DeFi and NFT that everyone 's talking about.",
    },
    table: {
      order: "Rank",
      name: "Name",
      type: "Type",
      chain: "Chain",
      user: "User",
      revenue: "Change",
      balance: "Balance",
      volume: "Volume",
      marketcap: "MarketCap",
      tvl: "TVL/Change",
      mcap: "MCap/TVL",
      highestYield: "Highest yield",
      highestPrice: "Highest price",
      costPrice: "Cost price",
      onlineTime: "Online time",
    },
  },
  info: {
    auditReports: "Audit",
    media: "Media",
    chain: "Chain",
    state: "State",
    status: "State",
    price: "Price",
    supply: "Supply",
    unit: "",
  },
  comment: {
    title: "Evaluation",
  },
  help: {
    title: "Participation Way",
    tutorial: "Tutorial",
    using: "{name}  tutorials",
  },
  share: {
    title: "Step",
    label: "Share",
    // message: 'Share the link 3 times to unlock the fortune code.',
    message: "A good new project in KingData: {link}, take a look",
    step: {
      count: "Share to 3",
      platform: "any platforms or friends",
      send: "Send shared screenshot to",
      join: "Join the group",
      wechat: "Communicate with industry leaders",
    },
    tutorial: "Tutorial link",
  },
  priceData: {
    high: "Highest yield",
    openHighPrice: "Highest price",
    openPrice: "Cost price",
    base: "Cost price",
    count: "Supply",
    floorPrice: "Floor price",
    mintPrice: "Mint price",
  },
  risk: {
    title: "Risk assessment description: ",
    tips: "The information provided on this website is a comprehensive evaluation based on the project intro, team, VCs, ecosystem, tokenomics, social media community, security audit, and other factors. It does not constitute investment advice, financial advice, trading advice, or any other sort of advice and you should not treat any of the website's content as such.",
  },
  empty: {
    title: "No more",
    text1: "View historical projects",
    text2: " or ",
    text3: "submit new projects",
  },
  project: {
    rec: "REC",
    audit: "Audit",
    media: "Media",
    contracts: "Token Contracts",
    whitePaper: "Whitepaper",
    dashboard: "Overview",
    symbol: "Token",
    symbolPrice: "Token Price",
    symbolSale: "Tokens for Sale",
    reviews: "Reviews",
    moreReviews: "View more reviews",
    news: "News",
    airdrop: "Airdrops",
    joinAirDrop: "Participate in airdrops",
    moreAirDrop: "More Airdrops",
    moreProject: "More Project",
    idoPrice: "IDO Price",
    owners: "Owners",
    fundraising: "Fundraising Goal",
    hoursUp: "24 hours up",
    hoursTrading: "24-hour trading volume",
    marketCap: "Market Cap",
    dilutedMarketCap: "Fully diluted market cap",
    circulationSupply: "Circulation supply",
    totalSupply: "Total Supply",
    maximumSupply: "Maximum supply",
    avgPrice: "Avg. Price",
    avgFloorPrice: "Avg. Floor Price",
    balance: "Balance",
    highestYield: "Highest yield",
    score: "Ratings",
    hoursSale: "24 hours sale",
    highestPrice: "Highest price",
    person: "Person",
    totalVolume: "Total volume",
    hotAirdrop: "Hot Airdrops",
    statistics: "Statistics",
    tvl: "TVL",
    floorPrice: "Floor Price",
    flash: "News",
    article: "Article",
    copy: "Copy Successfully",
    captured: "No Market Data Captured Yet",
    submit: "Submit Token Info",
    nodata: "No Data",
  },
  activity: {
    headLine: "🔥 KingData 2021",
    shortList: "Reasons for shortlist:",
    award: "Reason for award:",
    bannerTitle: "2021 KingData The BlueWhale Award",
    bannerHighTitle: "Annual Community Choice Project Awards",
    bannerDate: "Voting period: January 20 to 26, 2022",
    bannerRule: "Competition rules: The 5 most popular projects in each category will be awarded. The popularity score will be based on the number of ratings and number of votes.",
    bannerTip: "For cooperation and other concerns, please contact @Sue86393113 on Telegram.",
    title: "The BlueWhale Award",
    background: "Background Story:",
    backgrounTitle: "This award is named after KingData's mascot, the BlueWhale. The blue whale is the largest animal in the world and is known as the 'underwater giant.' However, it is very gentle in nature. In the vast ocean, the blue whale is free, rich in pursuit and courageous. At the same time, it is a symbol of uniqueness, signifying the future and the endless life force. The spirit pursued by the blockchain industry and practitioners is also freedom, pursuit, uniqueness, and courage.",
    backgroundHighTitle: "At the same time, the blue whale is an amazing disseminator of information. The wisdom of information dissemination is the quality conveyed to us by the blue whale, and KingData also takes this quality as its corporate spirit to efficiently disseminate effective industry information and data for the majority of users.",
    backgroundTip: "This time, the KingData BlueWhale Award will start with 6 major categories. They are the NFT Emerging List, GameFi Emerging List, DAO Emerging List, Infrastructure Emerging List, Public Chain Emerging List, and DEX Emerging List. The most popular projects of each category will be selected.",
    backgroundTips: "One of the objectives of this is to summarize the market for investors to help them find better investment targets and industry trends. On the other hand, it will also help projects to move forward in the blockchain industry and eventually become industry giants like the blue whale.",
    participation: "Participation methods:",
    participationOne: "(1) Fill up the application form.",
    participationTwo: "(2)  KingData will be the primary judge, and projects that pass the audit will be selected as finalists.",
    participationThree: "(3)  The projects will be polled and fans will vote for the projects they support on the KingData official voting page.",
    participationFour: "(4) Based on the number of votes, the top 5 projects in the 6 lists will be selected.",
    participationFive: "(5) 6 Top-5 projects (30 projects in total) will be presented at the award ceremony, and each Top 1 project will give a speech, and each from Top 2-5 projects will participate in the 6 roundtables.",
    project: "Project Registration",
    register: "Register",
    top: "Current top 5 projects",
    topTip: "{count} Projects",
    top5: `${oss}/common/Top5-en.png`,
    enter: `${oss}/common/enter-en.png`,
  },
  star: {
    title: "Tip",
    desc: "Success! To rate other items.",
    go: "Go",
  },
};
