export default {
  title: "One-stop investment platform on Web3",
  twoTitle: "Discover, Track, Invest DeFi, NFT, Gaming, Data-driven investing",
  platData: {
    avgAth: "Avg Revenue",
    desc: {
      title: "Criteria for assessing revenue:",
      content: "The returns represent KingData's selection of IDO & IGO projects. The average return of the top 100 projects. Do your own research. It's not a financial advice.",
    },
    nft: "NFT Projects",
    ido: "IDO/IGO Projects",
    air: "Airdrops Projects",
  },
  hotRecommend: "Recommended Topics",
  topTip: "During the last 24 hours：",
  todayTrend: {
    title: "Trends for today",
    time: "(Updated at 20:00)",
    key: "key word",
    pickTitle: "Daily trend interpretation",
    read: "people reading",
    updateTime: "Update time",
  },
  hotTopic: "Top Trends List",
  more: "More",
  lookMore: "More",
  loadingMore: "More",
  projectApply: "Apply",
  share: "Share",
  category: "Category",
  chain: "Chain",
  idoIgoProject: {
    title: "Data supported by 14 public chain and 65 platforms",
    all: "View more",
    chain: "Chain",
    upcoming: "Upcoming Projects",
    idoPrice: "IDO Price",
    totalRaised: "Total Raised",
    time: {
      day: "Day",
      hrs: "Hrs",
      min: "Min",
      sec: "Sec",
    },
    join: "Participate",
    ongoing: "Ongoing Projects",
    never: "Never miss an interesting NFT projects on KingData!",
  },

  nftProject: {
    price: "Price:",
    supply: "Supply:",
    time: {
      d: "d",
      h: "h",
      m: "m",
      s: "s",
    },
    mint: "Mint",
  },

  endProject: {
    title: "Projects Ended IDO & IGO",
    desc: "The latest Dapp projects are from 14 public chains and 68 IDO platforms",
    projectName: "Project Name",
  },

  topList: {
    name: "Project Name",
    chain: "Chain",
    rate: "Rating",
    plat: "TGE Platform",
    balance: "Balance",
    balance24h: "Balance(24h)",
    balance7d: "Balance(7d)",
    category: "Type",
    salePrice: "Sale Price",
    currentPrice: "Current Price",
    idoPrice: "IDO Price",
    volume: "Volume",
    volume24h: "Volume(24h)",
    volume7d: "Volume(7d)",
    marketCap: "MarketCap",
    floorPrice: "Floor price",
    mintPrice: "Mint price",
    mcap: "MCap",
    tokenSale: "Tokens for Sale",
    supply: "Supply",
    owner: "Owners",
    assets: "Assets",
    userChange: "User/Change",
    user24Change: "User(24h)/Change",
    user7Change: "User(7d)/Change",
    tvlChange: "TVL/Change",
    mcapChange: "MCap/Change",
    idoAth: "ATH Since lDO",
    nowCurrent: "Current ROI USD",
    endIn: "Ended in (UTC)",
    totalRaised: "Total Raised",
    noData: "No Data",
    changePercent24: "Volume%(24H)",
    changePercent7: "Volume%(7D)",
    whales_num: "Whales",
    whales_ratio: "Whales%",
    whale_num_change_24h: "whales_chang(24h)",
    whales_holding: "Whales_Holding",
    whale_holding_ratio: "Whales_Holding%",
    bule_chip_holders: "BC Holders",
    blue_chip_holders_change_24h: "BC Holders_change(24h)",
    blue_chip_holders_ratio: "BC Holders%",
    blue_chip_holding: "BC Holding",
    blue_chip_holding_ratio: "BC Holding%",
  },
  tagTop: "Tag Top 3",
  IdoIgo: {
    title: "Comprehensive aggregation platform for IDO",
    igotitle: "Comprehensive aggregation platform for IGO",
    desc: "Comprehensive Services: Web3.0,DeFi,GameFi,NFTs,Airdrops",
  },
  nfts: {
    title: "Comprehensive aggregation platform for NFT",
    desc: "Comprehensive Services: Web3.0,DeFi,GameFi,NFTs,Airdrops",
    today: "Today",
    tomorrow: "Tomorrow",
  },
  webInfo: {
    home: {
      title: "KingData | One-stop investment platform on Web3",
      key: "Discover, Track, Invest DeFi, NFT, Gaming, Web3.0,Airdrops,Data-driven investing",
      des: "Explore NFTs, NFT Marketplaces, Blockchain Games, De-Fi, Dapps On The Blockchain And More On The World’s DApp Store",
    },
    homeDetail: {
      title: "Recommended Topics | KingData",
      key: "Discover, Track, Invest DeFi, NFT, Gaming, Web3.0,Airdrops,Data-driven investing",
      des: "Find out the most popular trending items on KingData today, this week and this month",
    },
  },
  webIdo: {
    title: "List of IDO | KingData",
    key: "Discover, Track, Invest DeFi, NFT, Gaming, Web3.0,Airdrops,Data-driven investing",
    des: "List of upcoming token generation events and token sales",
  },
  webIgo: {
    title: "List of IGO | KingData",
  },
  webNft: {
    title: "List of NFTs | KingData",
    key: "Discover, Track, Invest DeFi, NFT, Gaming, Web3.0,Airdrops,Data-driven investing",
    des: "Popular NFTs, potential NFTs through the KingData project",
  },
  webAirdrop: {
    title: "List of Airdrop | KingData",
    key: "Discover, Track, Invest DeFi, NFT, Gaming, Web3.0,Airdrops,Data-driven investing",
    des: "We list the current exclusive crypto airdrops calendar, including cryptocurrencies, tokens and other cryptoassets.",
  },
  blog: {
    title: "Research",
    tips: "KingData reseach report, tracking the latest trends in Web3",
  },
  airdrop: {
    title: "OnGoing Airdrops",
    tips: "Collect the latest airdrop projects",
    airdrop: "Airdrops",
    tutorial: "Tutorial",
  },
  apy: {
    title: "We Find & Maximize DeFi and NFTs Vault Strategies",
    defi: "DeFi",
    nft: "NFTFi",
    alpaca: "Alpaca APY:",
    top: "Top 3 Vaults",
    deposit: "Deposit",
    more: "View More",
    tips: "Follow us and experience the latest features for the first time.",
  },
  new: {
    fund: "Fund",
    hot: "Hot projects of the week",
    wallet: "Connect Wallet",
    des1: "Automatically monitor changes in your assets and give investment advice.",
    followTip: "Follow us and experience the latest features for the first time.",
  },
};
