export default {
  projectName: "Project Name",
  yearFound: "Year Founded",
  time: "Last Funding",
  company: "Fundraising Rounds",
  fundProject: "Investment Projects",
  fundRound: "Fundraising Rounds",
  fundAmount: "Amounts",
  share: "Share",
  type: "Type",
  fundedRound: "Round",
  isSend: "Token",
  okSend: "Yes",
  noSend: "Not Yet",
  date: "Date",
  project: {
    title: "PROJECTS",
    subTitle: "KingData is a crypto platform for tracking private and public fundraising.",
    tipTitle: "We include latest information on seed, private, strategic, and IDO/IEO rounds.",
    round: "Round",
    sendRound: "Seed round",
    total: "Total:",
    investors: "investors",
    Investments: "Investments",
    totalRaised: "Total Raised",
    lastFund: "Last Funding",
    learnMore: "Learn More",
    funds: "FUNDS",
    trend: "Investment Trends",
  },
  page: {
    title: "Investment trends | KingData",
    key: "Discover, Track, Invest DeFi, NFT, Gaming, Web3.0,Airdrops,Data-driven investing",
    description: "List of crypto projects, with latest information on private and public funding",
  },
};
