export default {
  yearFound: "Year Founded",
  time: "Last Funding",
  company: "Fundraising Rounds",
  fundProject: "Investment Projects",
  fundRound: "Fundraising Rounds",
  fundAmount: "Fundraising Amounts",
  share: "Share",
  type: "Type",
  fundedRound: "Round",
  isSend: "Release Token",
  okSend: "Yes",
  noSend: "Not Yet",
  date: "Date",
  project: {
    title: "PROJECTS",
    subTitle: "KingData is a crypto platform for tracking private and public fundraising.",
    tipTitle: "We include latest information on seed, private, strategic, and IDO/IEO rounds.",
    round: "Round",
    sendRound: "Seed round",
    total: "Total:",
    investors: "investors",
    totalRaised: "Total Raised",
    lastFund: "Last Funding",
    learnMore: "Learn More",
    funds: "FUNDS",
    trend: "Investment Trends",
  },
};
