export default {
  yearFound: "Year Founded",
  lastFund: "Last Funding",
  company: "Fundraising Rounds",
  fundRound: "",
  share: "Share",
  type: "Type",
  fundRounds: "Fundraising Rounds",
  foundAmount: "投资金额",
  state: "是否发币",
  project: {
    title: "PROJECTS",
    subTitle: "KingData is a crypto platform for tracking private and public fundraising.",
    tipTitle: "We include latest information on seed, private, strategic, and IDO/IEO rounds.",
    round: "Round",
    sendRound: "Seed round",
    total: "Total:",
    investors: "investors",
    totalRaised: "Total Raised",
    lastFund: "Last Funding",
    learnMore: "Learn More",
    funds: "FUNDS",
    trend: "Investment Trends",
  },
};
