export default {
  users: "Users",
  balance: "Blance",
  chainVolume: "Transactions",
  mcapWithMaxSupplyTvl: "",
  tvl: "TVL",
  price: "price",
  currentRoi: "CurrentRoi",
  athPrice: "ATH",
  athRoi: "ATH_ROI",
  currentRoiFromAth: "Drop from ATH",
  atlPrice: "ATHL",
  volume: "Volume",
  mcapWithCirculationSupply: "MCap",
  mcapWithMaxSupply: "FDV",
  circulationSupply: "Circulating Supply",
  maxSupply: "Total Supply",
  owners: "Holders",
  avgPrice: "Avg_Price",
  buyer: "Buyer",
  seller: "Seller",
  buyerSeller: "Buyer/Seller",
  whales: "Whales",
  whalesRadio: "Whales Radio",
  volumeWithWhales: "Whales Holding",
  volumeWithWhalesRadio: "Whales Holding Radio",
  holdersFromBuleChip: "BC",
  holdersFromBuleChipRatio: "BC Holders Radio",
  volumeWithBuleChipHolder: "Whales Holding",
  volumeWithBuleChipHolderRadio: "Whales Holding Radio",
  tradeCount: "",
  avgProfiting: "Avg_Profit",
  profitTradeRadio: "Profit Orders Ratio",
  mintCount: "Mint Sold Num",
  mintProgress: "Mint Sold",
  mintTime: "Mint时间",
  buy_url: "",
  airdrop_url: "Airdrop_url",
  airdrop_amount: "Airdrop_Supply",
  airdrop_winner_count: "Airdrop_Num",
  airdrop_joined_user: "Users Joined",
  airdrop_symbol: "Airdrop_Token",
  airdrop_start_at: "Airdrop_start_at",
  airdrop_end_at: "Airdrop_end_at",
  ido_sale_amount: "",
  ido_price: "IDO_Price",
  ido_fundraising_goal: "Fundraising",
  ido_symbol: "Token_Symbol",
  ido_start_at: "IDO_Start",
  ido_end_at: "IDO_End",
  issue_volume: "Total Supply",
  mint_price: "Mint Price",
  mint_start_at: "Mint Start",
  mint_end_at: "Mint End",
  price_unit: "",
  data_source: "data_source",
  push_timestamp: "push_timestamp",
  push_to_app: "push_to_app",
  cmc_id: "cmc_id",
  src_logo_url: "src_logo_url",
  src_site: "src_site",
  src_name: "src_name",
  user_id: "User_id",
  user_telegram: "User_telegram",
  contact: "Contact",
  username: "Username",
  sort_num: "sort_num",
  is_top: "is_top",
  is_recommend: "Recommend",
  is_ad: "is_ad",
  is_featured: "is_featured",
  state: "state",
  is_nft_rank: "is_nft_rank",
  is_dapp_rank: "is_dapp_rank",
  is_potential_airdrop: "is_potential_airdrop",
  is_airdrop: "is_airdrop",
  is_igo: "is_igo",
  is_ido: "is_ido",
  is_mint: "is_mint",
  is_nft: "is_nft",
  is_dapp: "is_dapp",
  recommend_time: "recommend_time",
  update_time: "update_time",
  create_time: "create_time",
  publish_timestamp: "publish_timestamp",
  online_time: "online_time",
  name: "name",
  logo: "logo",
  website: "Website",
  website_domain: "website_domain",
  symbol: "Token",
  related_symbols: "Related_Tokens",
  gallery: "gallery",
  chains: "chains",
  categories: "categories",
  risk: "risk",
  description: "description",
  recommendation_reason: "recommendation_reason",
  long_description: "long_description",
  comment: "Comment",
  participation: "participation",
  participation_url: "participation_url",
  medias: "Medias",
  safety: "Audit",
  white_paper: "white_paper",
  contracts: "contracts",
  contract_list: "contract_list",
  community: "community",
  cover: "cover",
  tge_platform: "tge_platform",
  clout: "clout",
  sys_clout: "sys_clout",
  overall_score: "overall_score",
  score: "score",
  remark: "remark",
  shortlist_reason: "",
  award_reason: "",
  final_score: "",
  final_clout222222222222222222: "",
};
