/**
 * @file
 * @author zhangkun@163.com
 */
export default {
  share: {
    title: "Invite Friends",
    dec: "有用才分享，好用才推荐。区块链数据监控分析必备平台，快来和我一起快人一步，遇见财富吧！",
  },
  info: {
    vip: "VIP剩余天数",
    balance: "金币余额",
    set: "个人设置",
    avatar: "头像",
    nickname: "昵称",
    edit: "修改",
    phone: "手机",
    email: "邮箱",
    password: "密码",
    alreadyBind: "已绑定",
    goBind: "去绑定",
    noBind: "未绑定",
    editName: "修改昵称",
    inputName: "请输入昵称",
    emailVerify: "邮箱验证",
    message: "为了保护你的帐号安全，请验证身份",
    success: "绑定成功",
    error: "绑定失败，请稍后重试",
    tips: "该邮箱已被绑定，请换个邮箱",
    bindEmail: "绑定邮箱",
    editPassword: "修改密码",
  },
  hook: {
    title: "Vebhook binding",
    bindPlatform: "Binding platform",
    tgToken: "Telegram Token",
    messageHookList: "Message Hook List",
    platform: "Platform",
    token: "Token",
    language: "Language",
    operation: "Operation",
    bind: "Boot binding",
    use: "The usefulness of Webhook",
    useDec: "After the robot is pulled into the group and Tok is filled in the upper input box for binding, the robot will push the indicator newsletter that binds the account to the group for the first time.",
    create: "How to create a robot?",
    createDec: "Add BotFatheri as friends, click here to add Botfather",
    step: "The specific steps are as follows:",
    click: "click here",
    cnPush: "CN push",
    enPush: "EN push",
    desc: {
      desc1: "1. Add BotFatheri as friends，",
      desc2: " to add Botfather",
      desc3: "2. Open and Botfather the dialog box and send \"/newbot\". After this step, the Botfather will prompt you to enter the name of the robot you want to create. This name is optional, which is what we call it",
      desc4: "3. Set the name of the custom robot (this name is different from the name of the previous step, this name is unique) must end with \"_bot\" or \"Bot\" cannot contain Chinese, punctuation",
      desc5: "4. If the previous step is successfully executed, the Botfather will return the Token of the robot, which looks like this: 123456789: ABCDEfghiJK4314daDSadSa7",
      desc6: "Remember this Token, the robot will be created here",
    },
    dialogTitle: "Are you sure you want to delete the binding link?",
    dialogHolder: "Please fill in the Token and add it",
    dialogTips: "The Token is invalid, please add it again.",
    noData: "No Data",
    del: "Delete",
    support: "Support in succession",
  },
};
