/**
 * @file
 * @author zhangkun@163.com
 */
export default {
  share: {
    title: "Invite Friends",
    dec: "Useful to share, good to recommend. Blockchain data monitoring and analysis platform, to be first meeting the wealth!",
    submit: "Copy Share Link",
  },
  info: {
    vip: "VIP Remaining Days",
    balance: "Coin Balance",
    set: "Personal Settings",
    avatar: "Avatar",
    uploadAvatar: "Upload Avatar",
    nickname: "Nickname",
    edit: "Modify",
    phone: "Cell Phone",
    email: "E-mail",
    password: "Password",
    alreadyBind: "Bound",
    goBind: "De-Bind",
    noBind: "Unbound",
    editName: "Change Nickname",
    inputName: "Please Enter A Nickname",
    emailVerify: "Email Verification",
    message: "To protect your account security, please verify your identity",
    success: "Bind Successfully",
    passwordSuccess: "Successfully Modified",
    error: "Binding failed, please try again later",
    tips: "The email has been bound, please change the email address",
    bindEmail: "Binding Email Address",
    editPassword: "Modify Password",
  },
  hook: {
    title: "Webhook 绑定",
    bindPlatform: "绑定平台",
    tgToken: "Telegram Token",
    messageHookList: "Message Hook List",
    platform: "平台",
    token: "Token",
    language: "Language",
    operation: "Operation",
    bind: "引导绑定",
    use: "Webhook 的用处",
    useDec: "在机器人被拉入群组后，将Token填入上方输入框进行绑定后，您关注的指标，该机器人会第一时间推送会将账号绑定的指标快讯，推送至该群组。",
    create: "如何创建机器人？",
    createDec: "在 telegram 中我们可以通过和一个名为 BotFather 的机器人交互来申请自己的机器人",
    step: "具体步骤如下：",
    stepDec: "添加 BotFatheri 为好友，点击这里 添加 Botfather\n" + "打开和 Botfather 的对话框发送 “/newbot” 这一步过后Botfather会提示你输入你要创建的机器人的名字，这个名字可以随意，是我们称呼它的名字\n" + "设置自定义机器人的名字（这个名字不同于上一步的名字，这个名字是唯一的）结尾必须是  “_bot” 或者 “Bot” 不能包含中文，标点符号\n" + "如果上一步执行成功那么 Botfather 会返回该机器人的 Token，大概长这样：123456789：ABCDEfghiJK4314daDSadSa7\n" + "记住这个 Token，到这里机器人就创建好了",
    dialogTitle: "确定要删除该绑定链接吗？",
    dialogHolder: "请填写Token后添加",
    dialogTips: "该Token无效，请重新添加",
  },
};
