/**
 * @file
 * @author zhangkun@163.com
 */
export default {
  share: {
    title: "Invite Friends",
    dec: "Useful to share, good to recommend. Blockchain data monitoring and analysis platform, to be first meeting the wealth!",
    submit: "Copy Share Link",
  },
  info: {
    vip: "VIP Remaining Days",
    balance: "Coin Balance",
    set: "Personal Settings",
    avatar: "Avatar",
    uploadAvatar: "Upload Avatar",
    nickname: "Nickname",
    edit: "Modify",
    phone: "Cell Phone",
    email: "E-mail",
    password: "Password",
    alreadyBind: "Bound",
    goBind: "De-Bind",
    noBind: "Unbound",
    editName: "Change Nickname",
    inputName: "Please Enter A Nickname",
    emailVerify: "Email Verification",
    message: "To protect your account security, please verify your identity",
    success: "Bind Successfully",
    passwordSuccess: "Successfully Modified",
    error: "Binding failed, please try again later",
    tips: "The email has been bound, please change the email address",
    bindEmail: "Binding Email Address",
    editPassword: "Modify Password",
  },
  hook: {
    title: "Vebhook binding",
    bindPlatform: "Binding platform",
    tgToken: "Telegram Token",
    messageHookList: "Message Hook List",
    platform: "Platform",
    token: "Token",
    language: "Language",
    operation: "Operation",
    bind: "Boot binding",
    use: "The usefulness of Webhook",
    useDec: "After the robot is pulled into the group and Tok is filled in the upper input box for binding, the robot will push the indicator newsletter that binds the account to the group for the first time.",
    create: "How to create a robot?",
    createDec: "Add BotFather as friends, click here to add Botfather",
    step: "The specific steps are as follows:",
    click: "click here",
    cnPush: "CN push",
    enPush: "EN push",
    desc: {
      desc1: "1. Add BotFather as friends，",
      desc2: " to add Botfather",
      desc3: "2. Open and Botfather the dialog box and send \"/newbot\". After this step, the Botfather will prompt you to enter the name of the robot you want to create. This name is optional, which is what we call it",
      desc4: "3. Set the name of the custom robot (this name is different from the name of the previous step, this name is unique) must end with \"_bot\" or \"Bot\" cannot contain Chinese, punctuation",
      desc5: "4. If the previous step is successfully executed, the Botfather will return the Token of the robot, which looks like this: 123456789: ABCDEfghiJK4314daDSadSa7",
      desc6: "Remember this Token, the robot will be created here",
    },
    dialogTitle: "Are you sure you want to delete the binding link?",
    dialogHolder: "Please fill in the Token and add it",
    dialogTips: "The Token is invalid, please add it again.",
    noData: "No Data",
    del: "Delete",
    support: "Support in succession",
  },
};
