export default {
    myWallet:'My Wallet',
    tokenError:'Invalid Address',
    selectTip:'Enter the address you want to view',
    moneyManage:'Management',
    walletTip:'The connection will only be signed to authenticate your address attribution, not to authorize the credit',
    qhWallet:'Change Wallet',
    manageWallet:'Manage your wallet',
    lookAll:'View All',
    addFollow:'Add a follow address',
    addFollowTip:'Enter the address you want to follow',
    connectWallet:'Connect',
    walletManage:'Wallet Management',
    manageTxtTip:'Manage your assets',
    followList:'Follow List',
    export:'Export',
    betaForm:'Fill out the form to reserve your place',
    betaFormButton:'Reserved quota',
    connectWalletMessage:{
        noBeta:'The function is in testing, the use of the place is gradually open...',
        connectNumber:'Only one wallet can be connected per person in the feature internal test',
        followNumber:'In the internal test, each person can only follow two addresses other than the large account address',
    },
    history:'Recently Viewed',
    TrackWallet:'Track Any Wallet',
}
