<template>
  <div class="px-4">
    <div class="w-full text-center text-kd16px18px md:text-kd20px24px font-bold my-3 md:my-4">KingData Platform Service Agreement</div>
    <pre class="txt font-kdFang whitespace-pre-wrap">
Welcome to use KingData platform!
In order to use KingData platform services (hereinafter referred to as "the service"), you should read and abide by the "KingData Platform Service Agreement" (hereinafter referred to as the "Agreement"). Please read carefully and fully understand the content of each clause, especially the clauses for exemption or limitation of liability, and the separate agreement for opening or using a certain service, and choose to accept or not. Restrictions and exemptions may be in bold form to remind you to pay attention.
Unless you have read and accepted all the terms of this agreement and related agreements, you have no right to use this service. Your actions such as logging in, viewing, and publishing information to this service shall be deemed to have read and agree to the constraints of this agreement.
If you are under the age of 18, please read this agreement and other aforementioned agreements with your legal guardian, and pay special attention to the terms of use for minors.

<b>Note: The services under this agreement are still under development and update. Some services are temporarily unavailable. The specific content is subject to the actual services provided by the KingData platform. Thank you for your understanding and cooperation.</b>

1. Scope of the agreement
1.1 This agreement is an agreement between you and KingData regarding your use of KingData platform services. "Platform users" refer to individuals or organizations that register, log in, and use KingData platform accounts, and are more often referred to as "you" in this agreement. "Other users" refer to users related to this service, including subscribers, other than the platform users themselves.
1.2 This service uses KingData business platforms, including but not limited to KingData.com, KingData software, and KingData M stations, as communication channels. KingData provides platform users with services such as information release and brand promotion. After platform users register for a KingData platform account, they can use the KingData platform to perform operations such as information publishing, brand promotion, and subscription user comment management.

2. Account registration and account permissions
2.1 You need to register a KingData platform account before using this service. The KingData platform account is generated by e-mail binding.
2.2 KingData platform will review your registered account information. You should be solely responsible for the authenticity, legality, accuracy and validity of the account information you provide. If this causes damage to KingData or a third party, you should compensate according to law.
2.3 KingData has the right to modify the messages (including but not limited to text, pictures, videos, charts, etc.) that you publish through the KingData platform without changing the original intention, and to include but not limited to KingData network, KingData software, KingData M station Wait for the KingData business platform to push to the public. KingData and its affiliates and partners have worldwide, permanent, irrevocable, free, and non-exclusive rights to use any content you upload and publish through the KingData platform.
2.4 Using this service, you can obtain the following permissions:
2.4.1 Message management and interaction with subscribers through the KingData platform
2.4.2 Get the number of subscribers and message clicks of your KingData platform account
2.4.3 With KingData's consent, you have the right to publish brand promotion information and/or paid subscriptions and other commercial activities through the KingData platform. You also agree that KingData has the right to charge technical service costs for your commercial activities through the KingData platform.

3. Personal information protection of platform users
3.1 In the process of applying for this service, you may need to provide some necessary information. Please keep this information true, accurate, legal, and effective, and pay attention to timely update, so that KingData can provide you with timely and effective help, or better To provide you with services.
3.2 KingData and platform users are committed to the protection of personal information. It is a basic principle of KingData to protect the personal information of platform users. Without your consent, KingData will not disclose your personal information to any company, organization or individual other than KingData, unless otherwise provided by laws and regulations.
3.3 You should fully respect the personal information of anyone, including but not limited to other users, that you understand, receive, or have access to through this service, and you should not collect, copy, store, disseminate, or use it in any other way The personal information of other users, otherwise, the consequences arising therefrom shall be borne by you.

4. the platform content specification
4.1 The content of the platform mentioned in this article refers to any content produced, copied, published, or disseminated during your use of this service, including but not limited to registration information such as KingData platform account avatar, name, platform user description, or text, voice, etc. Sending, replying or automatically replying to messages and related linked pages of pictures, videos, graphics, etc., and other content generated by using KingData platform accounts or KingData platform services.
4.2 When you use this service, you need to comply with the "seven bottom lines" requirements of laws and regulations, national interests, collective interests, citizens' legal rights, social public order, morals, and information authenticity.
4.3 You may not use this service to produce, copy, publish, or disseminate the following contents prohibited by laws, regulations and policies:
(1) Those who oppose the basic principles established by the Constitution
(2) Endangering national security, leaking state secrets, subverting state power, and undermining national unity
(3) Damage to national honor and interests
(4) Inciting ethnic hatred, ethnic discrimination, and undermining ethnic unity
(5) Those who undermine national religious policies and promote cults and feudal superstitions
(6) Spread rumors, disrupt social order, and undermine social stability
(7) Spreading obscenity, pornography, gambling, violence, homicide, terror, or instigating crime
(8) Insulting or slandering others, infringing on the legal rights and interests of others
(9) Inciting illegal assemblies, associations, processions, demonstrations, gathering crowds to disrupt social order
(10) Acting in the name of an illegal civil organization
(11) Information containing other content prohibited by laws, regulations and policies.
4.4 You understand and agree that KingData has always been committed to providing platform users with a civilized, healthy, standardized and orderly network environment. You may not use this service to make, copy, publish, and disseminate the following to interfere with the normal operation of the KingData platform, or infringe on other users or third parties. The content of the legitimate rights and interests of the three parties:
(1) Contains any sexual or sexual suggestion
(2) Advertising, harassment, and spam
(3) Involving the privacy, personal information or data of others
(4) Infringement of legal rights such as reputation rights, portrait rights, intellectual property rights, and trade secrets of others
(5) Contains other information that interferes with the normal operation of the KingData platform and infringes the legitimate rights and interests of other users or third parties.

5.platform usage rules
5.1 The use of the platform mentioned in this article refers to any behavior you use this service, including but not limited to registration and login, account operation promotion, and other behaviors using KingData platform accounts or KingData platform services.
5.2 You may not use KingData platform account or KingData platform services to perform the following actions:
(1) Submitting or publishing false information, or impersonating or using the name of another person
(2) Force or induce other users to follow, click on linked pages or share information
(3) Fictional facts, concealing the truth to mislead or deceive others
(4) Infringement of legal rights such as reputation rights, portrait rights, intellectual property rights, and trade secrets of others
(5) The use of KingData platform account to promote for a third party without the written permission of KingData (including but not limited to adding third-party links, advertisements, etc.)
(6) Use plug-ins, plug-ins or other third-party tools or services to access this service and related systems without KingData’s written permission
(7) Use KingData platform account or KingData platform services to engage in any illegal or criminal activities
(8) Making and publishing methods and tools related to the above behaviors, or operating or disseminating such methods and tools, regardless of whether these behaviors are for commercial purposes
(9) Any behavior that destroys or attempts to disrupt network security (including but not limited to phishing, hackers, network fraud, spreading viruses, Trojan horses, malicious code, and suspected attacks on other websites and servers through virtual servers, etc.)
(10) Other acts that violate laws and regulations, infringe on the legitimate rights and interests of other users, interfere with the normal operation of the product, or are not expressly authorized by KingData.

6.account management
6.1 After the KingData platform user completes the application registration procedures, he obtains the right to use the KingData platform account. The right to use belongs only to the initial registrant, and it is forbidden to gift, borrow, rent, transfer or sell.
6.2 You should properly keep your login account and password, and take full responsibility for all actions performed using the account and password.
6.3 You should abide by the terms of this agreement and use this service correctly and appropriately. If you violate any clause in this agreement, you will terminate the provision of services to your KingData platform account in accordance with this agreement. At the same time, KingData reserves the right to withdraw the KingData platform account and platform user name at any time.

7.data storage
7.1 KingData is not responsible for the deletion or storage failure of your related data in this service.
7.2 KingData has the right to determine the maximum storage period of data in this service for a single platform user according to the actual situation, and allocate the maximum storage space for data on the server. You can back up the relevant data in this service according to your own needs.
7.3 If you stop using the service or the service is terminated or cancelled, KingData can permanently delete your data from the server. After the service is stopped, terminated or cancelled, KingData has no obligation to return any data to you.

8. Risks and exemptions
8.1 You understand and agree that this service only provides a platform for platform users to share, disseminate and obtain information. You must be responsible for all actions under your registered account, including the authenticity, legality, accuracy, and accuracy of the content you publish. Validity, and assume any results arising from the use of this service. Platform users should make their own judgments on the content in the KingData platform and bear all risks arising from the use of the content, including the risks arising from the reliance on the authenticity, legality, accuracy, and validity of the content. KingData cannot and will not be liable for loss or damage caused by platform user behavior.
If you find anyone violating the provisions of this agreement or using the KingData platform services in other improper ways, please report or complain to the KingData platform immediately, and we will deal with it in accordance with the law.
8.2 You understand and agree that, due to business development needs, KingData reserves the right to unilaterally change, suspend, restrict, terminate or revoke all or part of the service content at any time without any notice. The platform user shall bear the right This risk.
8.3 KingData may unilaterally suspend or terminate the use of KingData platform services by such accounts based on its judgment. If you violate this agreement, KingData may unilaterally suspend or terminate your use of KingData platform services and related account permissions .

9. Intellectual Property Statement
9.1 The intellectual property rights of the content provided by KingData in this service (including but not limited to works, pictures, audio, video, diagrams, files, information, data, website structure, website screen arrangement, web design, etc.) belong to KingData. The intellectual property rights of the content generated by the platform users in the use of this service belong to the platform users or relevant right holders.
9.2 Unless otherwise specified, the copyright, patent rights and other intellectual property rights of the software on which KingData provides this service belong to KingData.
9.3 The intellectual property rights of the above and any other content contained in this service are protected by law. Without the written permission of KingData, platform users or related rights holders, no one may use or create related derivative works in any form.

10. Legal Liability
10.1 If KingData finds or receives reports from others or complaints that platform users violated this agreement, KingData has the right to delete relevant content at any time without notice, and imposes but not limited to warnings, deletions, or parts of accounts that violate the rules according to the circumstances of the behavior. All subscribed users, restriction or prohibition of using all or part of the functions, account banning to cancellation penalties, and announcement of the processing results.
10.2 You understand and agree that KingData has the right to punish violations of relevant laws and regulations or the provisions of this agreement based on reasonable judgments, take appropriate legal actions against anyone who violates laws and regulations, and save relevant information in accordance with laws and regulations to report to relevant departments Etc., platform users shall bear all legal responsibilities arising from this alone.
10.3 You understand and agree that for any claims, demands or losses claimed by any third party, including reasonable attorney fees, caused or incurred by your violation of the provisions of this agreement or related terms of service, you shall compensate KingData and its partner companies, Affiliate companies to protect them from damage.

11. Entry into force and change of the agreement
11.1 Your use of this service is deemed to have read and agree to be bound by this agreement.
11.2 KingData reserves the right to modify the terms of this agreement when necessary. You can check the latest version of the terms of the agreement on the relevant service page.
11.3 After the terms of this agreement are changed, if you continue to use KingData platform services, you will be deemed to have accepted the revised agreement. If you do not accept the revised agreement, you should stop using this service.

12. Other
12.1 The headings of all the terms of this agreement are only for reading convenience, they have no actual meaning and cannot be used as the basis for interpretation of the meaning of this agreement.
12.2 No matter the terms of this agreement are partially invalid or unenforceable for any reason, the remaining terms are still valid and binding on both parties.
    </pre>
  </div>
</template>
<style scoped>
.txt {
  @apply text-kd14px20px;
}
</style>
