export default {
  disclaimers: "免责声明",
  title: "快速发现高收益矿池",
  apply: "申请收录",
  projectType: {
    all: "全部",
    mining: "挖矿",
    lending: "借贷",
  },
  miningTitle: "快速发现高收益矿池",
  loanTitle: "快速发现借贷最佳路径",
  platDes: "{chain} 条公链，{project} 个项目，{pool} 个池子，支持链对比，历史趋势，APP 提醒",
  allChain: "全部公链",
  chain: "选择公链",
  loanListChain: "公链",
  searchTxt: "搜索",
  searchProject: "搜索项目",
  search: "搜索币种",
  notice: "公告",
  tutorial: "教程",
  selectPlat: "选择平台",
  selectCoin: "选择币种",
  playType: {
    plat: {
      title: "我已选定平台",
      des1: "去投",
      high: "收益最高",
      des2: "的币种",
    },
    coin: {
      title: "我有币",
      des1: "去投",
      high: "收益最高",
      des2: "的平台",
    },
    loan: {
      title: "我要借款",
      des1: "去选择",
      high: "利息最低",
      des2: "的币种",
    },
  },
  my: "自选",
  total: "综合",
  single: "单利",
  more: "加载更多",
  miningChartTitle: "单币挖矿收益率",
  loanChartTitle: "单币借贷利率",
  chainType: "公链类型",
  poolType: "矿池类型",
  poolTag: "矿池策略",
  apyGroup: "APY 构成",
  singleInterest: "单利收益",
  compoundInterest: "复利收益",
  remainRatio: "剩余额度",
  hasMoney: "可投额度",
  remainHasMoney: "剩余可投额度",
  miningFarm: "去挖矿",
  lendFarm: "去挖矿",
  viewChart: "查看图表",
  viewToken: "查看币种",
  searchAll: "搜索币种/项目",
  project: "项目名称",
  projectTutorial: "项目教程",
  comLink: "访问官网",
  pools: "池子",
  tokens: "币种",
  highApy: "最高 APY",
  ok: "确定",
  moreToken: "更多币种",
  selectCoins: "更多",
  farmApyList: "挖矿收益榜单",
  loanList: "借贷利率榜",
  realCalculator: "真实利率计算器",
  calculator: "真实利率计算器",
  lever: "杠杆倍数",
  projects: "全部项目",
  all: "全部",
  singleCoin: "单币",
  operate: "操作",
  loanCoin: "借出币",
  borrowMoney: "可借金额",
  borrowAmount: "可借额度",
  interestGroup: "利率构成",
  loanListDes: "抵押借贷最佳路径",
  plat: "平台",
  mortgage: "抵押收益",
  borrowApy: "借出利率",
  borrowNumber: "借出金额",
  cost: "真实成本",
  projectTvl: "项目总TVL(多链)",
  userMoney: "用户总收益(多链)",
  supprotChain: "支持公链",
  poolNumber: "池子个数",
  projectView: "项目数据总览",
  addPool: "添加矿池",
  unaudited: "未审计",
  dayUser: "日活用户",
  projectRevenue: "项目收入",
  platCoinPrice: "平台币价格",
  sameProjectData: "同类项目数据",
  loanRouter: "借贷 {value} 的最佳路径",
  lowestLtv: "最低抵押率",
  clearRatio: "清算率",
  mortgageInterest: "抵押收益",
  rankCompare: "排行对比",
  trend: "走势图",
  trendCompare: "趋势对比",
  poolCompare: "池子对比",
  relatedLoanTrend: "相关借贷指标走势图",
  loanTopBest: "{value} 借款 TOP5 最优利率对比图",
  unitTiao: "条",
  projectDes: "项目描述",
  timeFormat: "YYYY年M月DD日",
  miningPool: "挖矿池子",
  loanPool: "借贷池子",
  projectData: "项目数据",
  selectedPool: "已选矿池",
  allMiningPool: "所有挖矿池子",
  allLoanPool: "所有借贷池子",
  addLoanPool: "添加借贷池子",
  projectLook: {
    userMoney: "用户总收益",
    borrowMoney: "借款总额",
    intoMoney: "存款总额",
    poolNumber: "总池子数",
    singlePoolNumber: "单币池子数",
    lpPoolNumber: "LP池子数",
    unit: "个",
  },
  addProject: "添加项目",
  selectedProject: "已选项目",
  loanMoneyCoin: "借款币种",
  loanApr: "借款 APR",
  miningApy: "挖矿 APY",
  noData: "暂无数据",
  loanPlat: "借贷平台",
  pleaseSelect: "请选择",
  diyaCoin: "抵押币种",
  diyaRato: "抵押率",
  jiechuCoin: "借出币种",
  jiekuanMoney: "借款成本",
  nowRato: "当前抵押率",
  noLow: "不得低于",
  realRato: "真实利率",
  clearData: "重置",
  loanAllRouter: "借贷 {token} 的所有最佳路径",
  warning: "风险提示",
  description: "风险提示：本站数据来源于各平台",
  warningDes: "本站数据来源于各平台的公开数据，本站井未对收录内容做安全审计，内容不构成投资建议，请注意风险。",
  tokenMining: "挖矿相关APY",
  tokenLending: "借贷相关APR",
  tokenMiningTitle: "挖 {token} 收益率前5的池子",
  tokenLendingTitle: "借贷 {token} 利息最低的前5池子",
  tokenMiningListTitle: "{token} 所有池子 APY",

  topTitleMining: "{token} Top 5",
  topTitleLending: "{token} Top 5",
  projectTitleMining: "当前 APY Top 5 池子",
  projectTitleLending: "当前 APR Top 5 池子",
  tokenTitleMining: "当前 {token} 挖矿 APY TOP 5",
  tokenTitleLeding: "当前 {token} 借贷 APR TOP 5",
  goMining: "去挖矿",
  goLending: "去借贷",

  pageMining: {
    title: "快速发现高收益矿池",
    content: "收录5条公链，25个项目，1422个池子",
  },
  pageLoan: {
    title: "快速发现借贷最佳路径",
    content: "收录5条公链，25个项目，1422个池子",
  },
  pageProject: {
    title: "{project} 项目数据分析",
    content: "收录5条公链，25个项目，1422个池子",
    h3: {
      mining: "{project} 挖矿 APY Top 5 {pool}",
      loan: "{project} 借贷 APR Top 5 {pool}",
      data: "{project} {value}",
    },
  },
  pageToken: {
    title: "{symbol} APY 数据分析",
    content: "收录5条公链，25个项目，1422个池子",
  },
  pageHeco: {
    title: "全网首家HECO节点竞选数据",
    content: "HECO节点竞选数据趋势对比",
  },
};
