export default {
  login: "登录",
  register: "注册",
  apply: "申请收录",
  more: "更多",
  idea: "意见反馈",
  resetPassword: "重置密码",
  switchLogin: "返回登录",
  switchRegister: "注册账号",
  switchRorget: "忘记密码",
  phone: "手机号登录",
  email: "邮箱登录",
  phoneCreate: "手机号注册",
  emailCreate: "邮箱注册",
  phoneForget: "手机号找回",
  emailForget: "邮箱找回",
  emailUpdate: "邮箱修改",
  noData: "暂无信息",
  lang: "EN",
  loginOut: "退出",
  account: {
    email: {
      tips: "您暂未绑定邮箱，请尽快绑定",
      bind: "去绑定",
      bind2: "绑定邮箱",
    },
  },
  nav: {
    apply: "项目申请",
    about: { name: "产品介绍", href: "https://www.yuque.com/kingdata_growthpad/tlll4r/blz39c" },
    download: "下载 KingData APP",
    download2: "下载 APP",
    download3: "立即下载",
  },
  time: {
    date: "日期",
    dd: "天",
    hh: "小时",
    mm: "分钟",
    ss: "秒",
    value: {
      week: "{count}周前", // 周
      day: "{count}天前", // 星期
      hour: "{count}小时前", // 小时
      minute: "{count}分钟前", // 分钟
    },
    // 星期几
    week: "星期一 | 星期二 | 星期三 | 星期四 | 星期五 | 星期六 | 星期日",
    month: "一月 | 二月 | 三月 | 四月 | 五月 | 六月 | 七月 | 八月 | 九月 | 十月 | 十一月 | 十二月",
    startTime: "开始时间",
    endedTime: "剩余时间",
    // 倒计时
    countDown: {
      // 未开始
      started: {
        day: "{count} 天之后开始",
        hour: "{count} 小时后开始",
        minute: "{count} 分钟后开始",
      },
      // 未结束
      ended: {
        day: "{count} 天之后结束",
        hour: "{count} 小时后结束",
        minute: "{count} 分钟后结束",
      },
    },
  },
  title: {
    share: "分享至",
  },
  button: {
    copy: "复制",
    submit: "提交",
    confirm: "确认",
    close: "取消",
    review: "审核中",
    success: "审核完成",
    danger: "审核未通过",
    selected: "已选",
    more: "加载更多",
    share: "去分享",
    all: "全部",
    viewAll: "查看全部",
    goto: "去完成",
    prev: "上一页",
    next: "下一页",
    shut: "关闭",
    expandMore: "展开更多 | 展开更多 ({size})",
  },
  message: {
    verification: "获取验证码",
    verificationError: "请输入6位验证码！",
    passwordError: "请输入6至24位的密码！",
    new_password: "两次密码不一致",
    telError: "请输入正确的手机号",
    testing: "验证中 预计15分钟更新结果",
    checking24h: "验证中，预计24小时更新结果",
    get: "已得",
    copy: "已复制邀请链接",
    fail: "失败, 请重新验证",
    checked: "注册前请阅读",
    mailError: "邮箱格式不正确",
    copyAlert: "你已成功复制",
    checkValue: "请按住滑块，拖动到最右边",
    codeDialog: "滑动获取验证码",
    loginError: "账号或者密码输入有误！",
  },
  placeholder: {
    login: "自动登录",
    tel: "请输入手机号",
    email: "请输入邮箱",
    verification: "请输入验证码",
    password: "请输入密码",
    new_password: "请再次输入密码",
    search: "搜索",
    sort: "请选择排序方式",
  },
  and: "及",
  join: "加入",
  follow: "关注",
  repost: "转发",
  andRepost: "并转发",
  activity: "活动",
  user: {
    invite: "请输入邀请码（非必填）",
    read: "注册前请阅读",
    agreement: "《用户协议》",
    terms: "《服务条款》",
    use: "《使用须知》",
    push: "我同意接收来自 KingData 的邮件",
  },
  chat: {
    telegram: "电报",
    join: "加入",
    telegramGroup: "电报群",
    joinTelegram: "加入电报群",
    twitter: "Twitter",
    sina: "微博",
  },
  symbol: {
    plus: "+",
    divide: "瓜分",
    colon: "：",
  },
  api: {
    wrong: "系统异常，请稍后再试",
  },
  fixTip: {
    content1: "学习交流，问题反馈",
    content2: "",
    content3: "",
    comfirm: "加入电报群",
  },
  risk: {
    high: "高风险",
    medium: "中风险",
    low: "低风险",
    unknown: "未知风险",
  },
  site: {
    web: "官网地址",
    name: "网站",
  },
  dialogData: {
    tip: "提示",
    deleteDes: "删除后内容将无法恢复，您确定要删除该条测评/回复吗？",
    close: "取消",
    ok: "确认",
  },
  lock: {
    text1: "好空投一起撸，分享好友查看完整教程",
    text2: "通过以下方式分享有效",
    gain: "再获得",
    again: "继续分享",
    unlock: "名好友<i>点击该链接</i>助力，即可解锁完整内容",
    shared: "查看进度",
    success: "已解锁完整教程",
    progress: "解锁进度",
  },
  share: {
    telegram: "分享至Telegram",
    twitter: "分享至Twitter",
    link: "复制链接分享至群或好友",
  },
  validate: {
    title: "亲爱的用户:",
    desc: "本网站不支持来自中国大陆地区的用户。访问前请确认您不是来自上述国家或地区。",
  },
};
