export default {
  test: "项目评测",
  testDes: "发布优质测评成为「测评师」，有机会加入「科学家探讨群」，与行业大佬第一时间交流优质项目。",
  testing: "写评测",
  inputTip: "谈谈你对项目的看法吧 ~",
  become: "成为测评师",
  min: "分钟前",
  hour: "小时前",
  day: "天前",
  month: "月前",
  year: "年前",
  push: "发布",
  reply: "回复",
  top: "置顶",
  more: "展开更多回复",
  close: "收起",
  moreTest: "加载更多...",
  delete: "删除",
  warning: {
    min: "字数少于{count}字",
    max: "字数大于{count}字",
  },
  write: "写测评",
};
