import { oss } from "src/config/";
export default {
  title: "快人一步 投 DApp 好项目",
  apply: "提交新项目",
  group: {
    all: "全部类型",
    viewOnline: "查看已上线项目",
    search: "搜索项目",
  },
  header: {
    info: "项目信息",
    mediaData: "社媒数据",
    type: "项目类型",
    time: "上线时间(UTC)",
    operate: "操作",
    projectYield: "项目收益",
  },
  website: "查看更多",
  timeEnd: "剩余时间",
  sort: {
    timeDesc: "按上线时间降序",
    timeAsc: "按上线时间升序",
    priceDesc: "按价格降序",
    priceAsc: "按价格升序",
    clout: "热度排序",
    create_time: "时间排序",
    rec: "运营精选",
    history: "历史项目",
    online: "即将上线",
  },
  status: {
    success: `${oss}/image/dapp/ongoing_cn.png`,
    wait: "/assets/dapp/wait_cn.png",
  },
  page: {
    title: "KingData DApp 新项目榜单",
    content: "快速发现每个人都在谈论的最新 DApps、DeFi、NFT、游戏和网站。",
  },
  meta: {
    description: "KingData DApp 新项目榜单 快速发现每个人都在谈论的最新 DApps、DeFi、NFT、游戏和网站。",
  },
  rank: {
    title: "快速发现优质 DApp",
    chartTitle: "所有公链总 TVL",
    comparison: "显示对比",
    searchProject: "搜索项目",
    page: {
      title: "KingData DApp 排行榜",
      content: "快速发现热门 DApps、DeFi、NFT、游戏和网站",
      meta: "KingData 新项目榜单，在这里快速发现人们讨论最多的新产品，以及当下热门的 DeFi 、NFT、Game等 DApp 项目。旨在帮助项目方摆脱传统的冷启动方式，提供一个快速曝光的流量平台。",
    },
    table: {
      order: "排名",
      name: "名称",
      type: "类别",
      chain: "公链",
      user: "用户",
      revenue: "变化率",
      balance: "资产",
      volume: "交易量",
      marketcap: "市值",
      tvl: "TVL/变化率",
      mcap: "MCap/TVL",
      highestYield: "最高收益",
      highestPrice: "开盘最高价",
      costPrice: "成本价",
      onlineTime: "上线时间",
    },
  },
  info: {
    auditReports: "审计公司",
    media: "社交媒体",
    chain: "所在公链",
    state: "项目状态",
    status: "进行中",
    price: "当前价格",
    supply: "发行数量",
    unit: "条",
  },
  comment: {
    title: "项目评测",
  },
  help: {
    title: "参与方式",
    tutorial: "公链使用教程",
    using: "{name}  使用教程",
  },
  share: {
    title: "解锁财富密码",
    label: "分享",
    // message: '分享 3 次链接，解锁财富密码。',
    message: "我在 KingData 发现一个不错的新项目：{link}，你看看",
    step: {
      count: "分享至3个",
      platform: "任意平台或好友",
      send: "发送分享截图至",
      join: "加入优质项目讨论群",
      wechat: "和行业大佬交流信息",
    },
    tutorial: "教程链接",
  },
  priceData: {
    high: "最高收益",
    openHighPrice: "开盘最高价",
    openPrice: "成本价",
    base: "成本价",
    count: "发行数量",
    floorPrice: "当前地板价",
    mintPrice: "Mint 价格",
  },
  risk: {
    title: "风险评估说明：",
    tips: "该风险评估结果是根据 <i>项目赛道、团队实力、投资机构、生态、代币发行方案、社交媒体热度、安全审计</i>等因素综合进行评估所得评级，该评级仅代表KingData观点，不具备任何投资建议，投资者需谨慎进行操作。",
  },
  empty: {
    title: "暂无待上线项目",
    text1: "\"查看历史项目\"",
    text2: "，或",
    text3: " \"提交新项目\"",
  },
  project: {
    rec: "精选项目",
    audit: "审计",
    media: "社区",
    contracts: "代币合约",
    whitePaper: "白皮书",
    dashboard: "概览",
    symbol: "代币",
    symbolPrice: "代币价格",
    symbolSale: "代币出售",
    reviews: "测评",
    moreReviews: "查看更多评测",
    news: "资讯",
    airdrop: "空投",
    joinAirDrop: "参与空投",
    moreAirDrop: "更多空投",
    moreProject: "更多项目",
    idoPrice: "IDO 价格",
    owners: "持有人",
    fundraising: "筹款目标",
    hoursUp: "24H涨幅",
    hoursTrading: "24H交易量",
    marketCap: "市值",
    dilutedMarketCap: "完全稀释后市值",
    circulationSupply: "流通供应量",
    totalSupply: "总供应量",
    maximumSupply: "最大供应量",
    avgPrice: "平均成交价",
    avgFloorPrice: "平均地板价",
    balance: "资产",
    highestYield: "最高收益",
    score: "评分",
    hoursSale: "24H售卖",
    highestPrice: "开盘最高价",
    person: "人",
    totalVolume: "总交易量",
    hotAirdrop: "热门空投",
    statistics: "链上数据",
    tvl: "TVL",
    floorPrice: "地板价",
    flash: "快讯",
    article: "文章",
    copy: "复制成功",
    captured: "暂未捕获行情数据",
    submit: "提交代币信息",
    nodata: "暂无信息",
    projectInfo: "项目信息",
    platformTutorial: "详细教程：",
  },
  activity: {
    headLine: "🔥 KingData 2021",
    shortList: "入围理由:",
    award: "获奖理由:",
    bannerTitle: "2021 KingData 鲸鱼奖",
    bannerHighTitle: "年度项目评选",
    bannerDate: "评选日期：2022年1月20日-1月26日",
    bannerRule: "评选规则：每条赛道最受欢迎的5个项目将被授予奖项（评分数*投票数代表最终人气）",
    bannerTip: "如有合作意向以及其他需求请联系：Telegram @Sue8639313",
    title: "KingData鲸鱼奖",
    background: "背景介绍：",
    backgrounTitle: "此次颁奖典礼以 KingData 吉祥物蓝鲸命名，蓝鲸是世界上最大的动物，有“海底巨兽”之称，但性情十分温顺。茫茫大海中，蓝鲸是自由的、富有追求的、勇往直前的，同时又是独一无二的象征，寓意着未来和生生不息的生命力。自由，追求，独一无二，勇往直前也是整个区块链产业与从业者所追求的精神。",
    backgroundHighTitle: "同时，蓝鲸是惊人的信息传播者，信息传播的智慧是蓝鲸传达给我们的有力品质。KingData 也把这种品质作为企业精神，以为广大用户高效传播有效行业信息与数据为宗旨。",
    backgroundTip: "此次，KingData 鲸鱼奖将以6大赛道进行展开，分别为：NFT 新锐榜、 GameFi 新锐榜、 Dao 新锐榜、 基础设施新锐榜、 公链新锐榜、DEX 新锐榜。评选出2021年各个赛道最佳、最具潜力的明星项目，一方面；为投资者总结市场，找到更好的投资标地以及行业趋势，另一方面；助力明星项目在区块链产业中勇往直前，最终成为如蓝鲸一般的“行业巨兽”。",
    backgroundTips: "",
    participation: "参与方式：",
    participationOne: "（1）项目填写表单报名",
    participationTwo: "（2）KingData 官方初级评审，审核通过的项目入围",
    participationThree: "（3）参赛项目拉票，粉丝登录 KingData 官网投票页面为所支持的项目进行投票",
    participationFour: "（4）根据投票数，选出6大榜单 TOP5 项目",
    participationFive: "（5）6大榜单 TOP5 项目（共30个项目进入颁奖典礼，进行项目展示），每个榜单 TOP1 进行演讲，每个榜单 TOP2-TOP5 分别进行参与6大赛道圆桌会议",
    project: "项目报名",
    register: "报名",
    top: "当前Top5项目",
    topTip: "共 {count}家项目",
    top5: `${oss}/common/Top5.png`,
    enter: `${oss}/common/enter.png`,
  },
  star: {
    title: "提示",
    desc: "评分成功！去给更多榜单项目打分吧~",
    go: "去看看",
  },
  detail: {
    upcoming: "即将开始",
    ongoing: "进行中",
    ended: "已结束",
    tutorial: "参与教程",
    mintTime: "Mint 时间",
    airdropTime: "空投时间",
    activityTime: "活动时间",
    go: "Go To DApp",
    price: "代币价格{name}",
    mcapTvl: "TVL/MCap",
    tvl: "TVL",
    buy: "Buy Now",
    mcap: "市值(24H)",
    owners: "持有人(24H)",
    status: "阶段",
    airdrop: "空投",
    claimIt: "认领",
    winNumber: "获奖人数",
    airdropAmount: "空投总量",

    ido: "IDO",
    idoPrice: "IDO 价格",
    participate: "去参与",
    fundraisingRounds: "筹款回合",

    seed: "Seed",
    mint: "Mint",
    toMint: "铸造",
    mintSupply: "Mint 数量",

    holder: {
      holder: "持有人",
      whale: "巨鲸",
      holdNft: "持有趋势",
      blueChip: "蓝筹股持有人",
      holderTrend: "持有人数量",
      ratioTrend: "持有人变化趋势",
      nftTrend: "持有NFTs趋势",
      nftRatioTrend: "持有NFTs比率趋势",
      holderTips: "所有收题中持有NFT价值超过1,000,000美元的地址的数量和百分比至少持有该收题的一个NFT。",
      holdingTips: "鲸鱼持有的该集合中NFT的数量和百分比。",
      blueChipTips: "对于蓝筹股收题品，蓝筹股持有者必须持有至少一个来自该系列和任何其他蓝 筹股收题品的NFT。\n" + "对于非蓝筹股集合，蓝筹股持有者必须持有至少一个蓝筹股集合的NFT。",
      blueHoldingTips: "蓝筹股持有者持有的该集合中NFT的数量和百分比。",
      day: "近1月",
      all: "全部",
    },
    header: {
      items: "Items",
    },
  },
  not: {
    text1: "市场数据未经追踪",
    text2: "由于该项目相对较新，请查看我们的免责声明",
  },
  introduction: {
    title: "项目描述",
  },
};
