export default {
  title: "Web3 一站式投资平台",
  twoTitle: "发现、跟踪、投资 DeFi、NFT、游戏，数据驱动投资",
  loadData: "数据加载中，请稍后查看",
  platData: {
    avgAth: "平均收益",
    desc: {
      title: "收益计算说明：",
      content: "该收益为 KingData 平台所收录的 IDO & IGO 项目，收益排名前100的最高平均项目收益，数据可能存在一定的误差，仅作为参考，不具备任何投资建议，投资者需谨慎进行操作。",
    },
    nft: "NFT Projects",
    ido: "IDO/IGO Projects",
    air: "Airdrops Projects",
  },
  topTip: "过去 24 小时内的数据：",
  todayTrend: {
    title: "今日趋势",
    time: "(每日20:00更新)",
    key: "关键词",
    pickTitle: "",
    read: "人阅读",
    updateTime: "更新时间",
  },
  hotRecommend: "热门话题",
  hotTopic: "热门趋势榜单",
  more: "更多",
  lookMore: "查看全部",
  loadingMore: "加载更多",
  projectApply: "申请收录",
  share: "分享",
  category: "类别",
  platform: "平台",
  chain: "公链",
  idoIgoProject: {
    title: "聚合 14 条公链，68 个IDO平台最新优质 Dapp 项目",
    all: "查看全部",
    chain: "公链",
    upcoming: "Upcoming Projects",
    idoPrice: "IDO 价格",
    totalRaised: "筹款目标",
    time: {
      day: "Day",
      hrs: "Hrs",
      min: "Min",
      sec: "Sec",
    },
    join: "去参与",
    ongoing: "Ongoing Projects",
    never: "不要错过 KingData 上任何一个有趣的NFT项目!",
  },

  nftProject: {
    price: "价格：",
    supply: "总量：",
    time: {
      d: "d",
      h: "h",
      m: "m",
      s: "s",
    },
    mint: "Mint",
  },

  endProject: {
    title: "Ended IDO & IGO Projects",
    desc: "聚合 14 条公链，68 个IDO平台最新优质 Dapp 项目",
    projectName: "项目名",
  },

  topList: {
    name: "项目名称",
    chain: "公链",
    rate: "评分",
    plat: "来源平台",
    balance: "资产",
    balance24h: "资产(24h)",
    balance7d: "资产(7d)",
    category: "类型",
    salePrice: "售卖价格",
    currentPrice: "当前价格",
    idoPrice: "IDO 价格",
    volume: "交易量",
    volume24h: "交易量(24h)",
    volume7d: "交易量(7d)",
    marketCap: "MarketCap",
    floorPrice: "地板价",
    mintPrice: "MInt 价格",
    mcap: "MCap",
    tokenSale: "代币出售",
    supply: "发行数量",
    owner: "持有人",
    assets: "资产",
    userChange: "用户/变化率",
    user24Change: "用户(24h)/变化率",
    user7Change: "用户(7d)/变化率",
    tvlChange: "TVL/Change",
    mcapChange: "MCap/Change",
    idoAth: "自IDO以来收益",
    nowCurrent: "当前收益",
    endIn: "结束于(UTC)",
    totalRaised: "筹款目标",
    noData: "无数据",
    changePercent24: "交易量%(24H)",
    changePercent7: "交易量%(7D)",
    whales_num: "巨鲸Holders",
    whales_ratio: "巨鲸Holders%",
    whales_holding: "巨鲸持仓",
    whale_holding_ratio: "巨鲸Holding%",
    bule_chip_holders: "蓝筹Holders",
    blue_chip_holders_change_24h: "蓝筹Holders涨幅",
    blue_chip_holders_ratio: "蓝筹Holders%",
    blue_chip_holding: "蓝筹Holders持仓",
    blue_chip_holding_ratio: "蓝筹Holding占比",

    owners_change24: "持有人_涨幅(24h)",
    owners_change7: "持有人_涨幅(7d)",
    owners_change30: "持有人_涨幅(30d)",
    owners_change3: "持有人_涨幅(3M)",
    floor_price_change_24h: "地板价_涨幅(24h)",
    floor_price_change_7d: "地板价_涨幅(7d)",
    floor_price_change_30d: "地板价_涨幅(30d)",
    floor_price_change_3M: "地板价_涨幅(3M)",
    mcap_change_24h: "市值_涨幅(24h)",
    mcap_change_7d: "市值_涨幅(7d)",
    mcap_change_30d: "市值_涨幅(30d)",
    mcap_change_3M: "市值_涨幅(3M)",
    tvl_change_24h: "TVL_涨幅(24h)",
    avg_price_change_24h: "成交均价_涨幅(24h)",
    avg_price_change_7d: "成交均价_涨幅(7d)",
    avg_price_change_30d: "成交均价_涨幅(30d)",
    avg_price_change_3M: "成交均价_涨幅(3M)",
    whale_num_change_24h: "巨鲸Holders涨幅(24h)",
    whale_num_change_7d: "巨鲸Holders涨幅(7d)",
    whale_num_change_30d: "巨鲸Holders涨幅(30d)",
    whale_num_change_3M: "巨鲸Holders涨幅(3M)",
    whale_holding_change_24h: "巨鲸持仓涨幅(24h)",
    whale_holding_change_7d: "巨鲸持仓涨幅(7d)",
    whale_holding_change_30d: "巨鲸持仓涨幅(30d)",
    whale_holding_change_3M: "巨鲸持仓涨幅(3M)",
    volume_change_24h: "交易额涨幅(24h)",
    volume_change_7d: "交易额涨幅(7d)",
    volume_change_30d: "交易额涨幅(30d)",
    volume_change_3M: "交易额涨幅(3M)",
    ath_price_change_24h: "最高成交价涨幅(24h)",
    ath_price_change_7d: "最高成交价涨幅(7d)",
    ath_price_change_30d: "最高成交价涨幅(30d)",
    ath_price_change_3M: "最高成交价涨幅(3M)",
    sales_change_24h: "订单总数涨幅(24h)",
    sales_change_7d: "订单总数涨幅(7d)",
    sales_change_30d: "订单总数涨幅(30d)",
    sales_change_3M: "订单总数涨幅(3M)",
    profit_share: "盈利订单占比",
    mean_profiting_change_24h: "成单平均盈利涨幅(24h)",
    mean_profiting_change_7d: "成单平均盈利涨幅(7d)",
    mean_profiting_change_30d: "成单平均盈利涨幅(30d)",
    mean_profiting_change_3M: "成单平均盈利涨幅(3M)",
    buyer_change_24h: "买家_涨幅(24h)",
    buyer_change_7d: "买家_涨幅(7d)",
    buyer_change_30d: "买家_涨幅(30d)",
    buyer_change_3M: "买家_涨幅(3M)",
    seller_change_24h: "卖家_涨幅(24h)",
    seller_change_7d: "卖家_涨幅(7d)",
    seller_change_30d: "卖家_涨幅(30d)",
    seller_change_3M: "卖家_涨幅(3M)",
    mint_sell: "MINT 售出数量",
    mint_time: "Mint时间",
    comment: "推荐理由",
    invested_at: "融资日期",
    amount: "融资金额",
    stage_name: "投资阶段",
  },
  tagTop: "Tag Top 3",
  IdoIgo: {
    title: "最新最全的 IDO 聚合平台",
    igotitle: "最新最全的 IGO 聚合平台",
    desc: "一站式服务：Web3.0、DeFi、游戏、NFT、Airdrops",
  },
  nfts: {
    title: "最新最全的 NFT 聚合平台",
    desc: "一站式服务：Web3.0、DeFi、游戏、NFT、Airdrops",
    today: "今天",
    tomorrow: "明天",
  },
  webInfo: {
    home: {
      title: "KingData | Web3 一站式投资平台",
      key: "发现、跟踪、投资 DeFi、NFT、游戏、Web3.0、Airdrops、数据驱动投资",
      des: "在全球 DApp Store 上探索 NFT、NFT 市场、区块链游戏、De-Fi、区块链上的 Dapp 等",
    },
    homeDetail: {
      title: "热门话题 | KingData",
      key: "发现、跟踪、投资 DeFi、NFT、游戏、Web3.0、Airdrops、数据驱动投资",
      des: "快速查看今天、本周和本月 KingData 上最流行的趋势项目。",
    },
  },
  webIdo: {
    title: "IDO 列表 | KingData",
    key: "发现、跟踪、投资 DeFi、NFT、游戏、Web3.0、Airdrops、数据驱动投资",
    des: "即将举行的代币生成活动和代币销售列表",
  },
  webIgo: {
    title: "IGO 列表 | KingData",
  },
  webNft: {
    title: "NFTs 列表 | KingData",
    key: "发现、跟踪、投资 DeFi、NFT、游戏、Web3.0、Airdrops、数据驱动投资",
    des: "发掘热门NFT項目，通过 KingData 找出潜力NFT",
  },
  webAirdrop: {
    title: "Airdrop 列表 | KingData",
    key: "发现、跟踪、投资 DeFi、NFT、游戏、Web3.0、Airdrops、数据驱动投资",
    des: "我们列出了当前独家加密空投日历，包括加密货币、代币和其他加密资产。",
  },
  blog: {
    title: "研究文章",
    tips: "KingData 研报，带你捕获 Web3 最新趋势。",
  },
  airdrop: {
    title: "最新空投",
    tips: "行业最新最全空投都在这",
    airdrop: "项目",
    tutorial: "教程",
  },
  apy: {
    title: "快速发现高收益DeFi和NFTs金库",
    defi: "DeFi",
    nft: "NFTFi",
    alpaca: "Alpaca APY:",
    top: "Top 3 金库",
    deposit: "去挖矿",
    more: "查看更多",
    tips: "关注我们，第一时间体验最新功能",
  },
  new: {
    fund: "我的资产",
    hot: "本周热门项目",
    wallet: "连接钱包",
    des1: "自动监控您的资产变化，并给出投资建议",
    followTip: "关注我们，第一时间体验最新功能",
  },
};
