export default {
  yearFound: "成立年份",
  time: "最后的投资",
  company: "组合投资公司",
  fundProject: "投资项目数",
  fundRound: "投资次数",
  fundAmount: "投资金额",
  share: "分享此页面",
  type: "项目类型",
  fundedRound: "投资轮次",
  isSend: "是否发币",
  okSend: "已发币",
  noSend: "未发币",
  date: "日期",
  project: {
    title: "项目",
    subTitle: "KingData 是一个用于跟踪私人和公共筹款的加密平台。",
    tipTitle: "我们包括有关种子轮、私人轮次、战略轮次和 IDO/IEO 轮次的最新信息。",
    round: "投资轮次",
    sendRound: "种子轮",
    total: "总计:",
    investors: "投资者",
    totalRaised: "筹款总额",
    lastFund: "最后的投资",
    learnMore: "查看详情",
    funds: "机构",
    trend: "机构投资动向",
  },
};
