export default {
  message: {
    success: "复制成功",
  },
  share: "发现聪明的钱流向，大户、散户行为一目了然",
  description: "KingData DEX 分析 对MDEX中的流动性添加与撤出、交易数据进行了多维度多场景的详尽分析，对主力、散户行为一目了然，帮助用户提前发现市场中的异常，分析价格变动的原因和不同指标的相关性。",
  numberUnit: {
    wan: "万",
    yi: "亿",
    wanyi: "万亿",
  },
  comingsoon: "即将开放",
  noData: "暂无数据",
  address: "地址",
  webTitle: "KingData DEX 分析",
  mobile: {
    select: "搜索",
    selectDes: "查看自选或搜索币种",
    flow: "流动性分析",
    pay: "交易数据分析",
    time: "选择时间",
    interval: "时间粒度",
    pairDesc: "相关交易对",
    pcDes1: "为了您良好的使用体验",
    pcDes2: "该功能仅限在电脑中访问",
    confirm: "确定",
  },
  select: {
    tip: "搜索币种/交易对/合约地址",
    coinType: "币种",
    tradingPairs: "交易对",
    more: "查看更多",
    history: "历史记录",
    hot: "热门搜索",
    address: "合约地址",
    price: "价格",
    changePrice: "汇率价格",
  },
  info: {
    tokenAddress: "合约地址",
  },
  side: {
    self: "自选",
    pairDesc: "相关交易对",
    tvlNumber: "锁仓量",
    pair: "交易对",
    tvl: "TVL($)",
    price: "价格",
    change: "涨跌幅",
    rate: "汇率",
  },
  mainHeader: {
    liquidity: "{token} 所有相关的交易对数据聚合分析",
    payData: "仅对 {pair} 交易对相关的数据聚合分析",
    follow: "关注",
    analysis: "分析数据异常",
    week: "近7天",
    twoWeek: "近14天",
    month: "近1月",
    streeMonth: "近3月",
    sixMonth: "近6月",
    year: "近1年",
    custom: "自定义",
    all: "全部",
    usd: "USD计价",
    coin: "币本位计价",
    bottom: "已到底部",
  },
  titleCofig: {
    moneyReplaceStr: "资金明细",
    numberReplaceStr: "频次",
    money: " {value} 资金明细",
    number: " {value} 频次",
  },
  mainChart: {
    moneyInto: {
      title: "资金净流入",
      desc: "展示选定币种或者交易对的相关资金净流入情况。资金的净流入方向一定程度上代表着用户对产品的认可程度，对后市价格也影响较大。",
    },
    IntoInOutAnalysis: {
      title: "流入流出明细",
      desc: "展示选定币种或者交易对的相关资金净流入流出的明细，更直观的展示资金在多空博弈时的体量。",
    },
    IntoInOutNumber: {
      title: "流入流出频次",
      desc: "展示选定币种或者交易对的用户操作的频率，能直观的反映人们参与的热情。",
    },
    joinUsersAnalysis: {
      title: "参与人数分析",
      desc: "展示选定币种或者交易对的参与人数的明细，能直观的看出相关项目的用户规模。",
    },
    addUsersAnalysis: {
      title: "新增人数分析",
      desc: "展示选定币种或者交易对的新增用户的明细，能直观的看出相关项目有多少新用户进入。",
    },
  },
  fullChart: {
    tip: "* 点击柱图可进行数据过滤",
  },
  down: {
    address: "地址",
    pair: "交易对",
    netAdd: "净添加量",
    add: "添加总量",
    remove: "移除总量",
    times: "参与次数",
    addTimes: "添加次数",
    removeTimes: "移除次数",
    addLiquidity: "添加流动性",
    removeLiquidity: "撤出流动性",
    time: "时间",
    direction: "方向",
    netBuy: "净买入",
    buy: "买入",
    sell: "卖出",
    payTimes: "交易笔数",
    buyTimes: "买入笔数",
    sellTimes: "卖出笔数",
    value: "总价值",
    details: "数据详解",
    chartTip: "点击列表地址可对图表数据过滤",
    chartTipTwo: "点击柱图可进行数据过滤",
    loading: "加载中...",
    pull: "上拉加载更多",
    noMore: "没有更多了",
  },
};
