/**
 * @file
 * @author zhangkun@163.com
 */
export default {
  share: {
    title: "邀请好友",
    dec: "有用才分享，好用才推荐。区块链数据监控分析必备平台，快来和我一起快人一步，遇见财富吧！",
    submit: "复制分享链接",
  },
  info: {
    vip: "VIP剩余天数",
    balance: "金币余额",
    set: "个人设置",
    avatar: "头像",
    uploadAvatar: "上传头像",
    nickname: "昵称",
    edit: "修改",
    phone: "手机",
    email: "邮箱",
    password: "密码",
    alreadyBind: "已绑定",
    goBind: "去绑定",
    noBind: "未绑定",
    editName: "修改昵称",
    inputName: "请输入昵称",
    emailVerify: "邮箱验证",
    message: "为了保护你的帐号安全，请验证身份",
    success: "绑定成功",
    passwordSuccess: "修改成功",
    error: "绑定失败，请稍后重试",
    tips: "该邮箱已被绑定，请换个邮箱",
    bindEmail: "绑定邮箱",
    editPassword: "修改密码",
  },
  hook: {
    title: "Webhook 绑定",
    bindPlatform: "绑定平台",
    tgToken: "Telegram Token",
    messageHookList: "Message Hook List",
    platform: "平台",
    token: "Token",
    language: "语言",
    operation: "操作",
    bind: "引导绑定",
    use: "Webhook 的用处",
    useDec: "在机器人被拉入群组后，将 Token 填入上方输入框内进行绑定，该机器人会第一时间推送账户关注的指标快讯至该群组。",
    create: "如何创建机器人？",
    createDec: "在 Telegram 中我们可以通过和一个名为 BotFather 的机器人交互来申请自己的机器人",
    step: "具体步骤如下：",
    click: "点击这里",
    cnPush: "中文推送",
    enPush: "英文推送",
    desc: {
      desc1: "1. 添加 BotFatheri 为好友，",
      desc2: " 添加 Botfather",
      desc3: "2. 打开和 Botfather 的对话框发送 “/newbot” 这一步过后Botfather会提示你输入你要创建的机器人的名字，这个名字可以随意，是我们称呼它的名字",
      desc4: "3. 设置自定义机器人的名字（这个名字不同于上一步的名字，这个名字是唯一的）结尾必须是  “_bot” 或者 “Bot” 不能包含中文，标点符号",
      desc5: "4. 如果上一步执行成功那么 Botfather 会返回该机器人的 Token，大概长这样：123456789：ABCDEfghiJK4314daDSadSa7",
      desc6: "记住这个 Token，到这里机器人就创建好了",
    },
    dialogTitle: "确定要删除该绑定链接吗？",
    dialogHolder: "请填写Token后添加",
    dialogTips: "该Token无效，请重新添加",
    noData: "暂无信息",
    del: "删除",
    support: "陆续支持中",
  },
};
