export default {
    myWallet:'我的钱包',
    tokenError:'无效Address',
    selectTip:'输入您要查看的地址',
    moneyManage:'资产管理',
    walletTip:'连接只会进行签名认证您的地址归属，不会进行额度授权',
    qhWallet:'切换钱包',
    manageWallet:'管理钱包',
    lookAll:'查看全部',
    addFollow:'添加关注地址',
    addFollowTip:'输入您要关注的地址',
    connectWallet:'连接钱包',
    walletManage:'钱包管理',
    manageTxtTip:'管理您的资产',
    followList:'关注列表',
    export:'Export',
    betaForm:'填写表单，预约使用名额',
    betaFormButton:'预约使用名额',
    connectWalletMessage:{
        noBeta:'功能正在内测中，使用名额正在逐步开放中...',
        connectNumber:'功能内测中,每人只能连接一个钱包',
        followNumber:'功能内测中,每人只能关注两个大户地址外的地址',
    }
}
