name: build for dev

on:
  pull_request:
    branches: [ dev ]
    types:
      - closed
jobs:
  dev_auto_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: ${{ steps.login-ecr.outputs.registry }}/kd-web4:dev-${{ steps.slug.outputs.sha8 }}
          file: ./DockerfileTest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

#
#      - name: deploy to cluster kd-web3
#        uses: kodermax/kubectl-aws-eks@master
#        env:
#          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#          IMAGE_URL: '${{ steps.login-ecr.outputs.registry }}/kd-web3:dev-${{ steps.slug.outputs.sha8 }}'
#        with:
#          args: set image -n dev deployment/kd-web3-v1 container-z1cfk3=$IMAGE_URL
#
#      - name: verify deployment kd-web3
#        uses: kodermax/kubectl-aws-eks@master
#        env:
#          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#        with:
#          args: rollout status -n dev deployment/kd-web3-v1
